name: Build Container Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Get latest release
        id: kaniko
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: GoogleContainerTools/kaniko

      - name: Get latest release
        id: jq
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: stedolan/jq

      - name: Get latest release
        id: yq
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: mikefarah/yq

      - name: Get latest release
        id: pushrm
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: christian-korneck/docker-pushrm

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          build_args: >-
            KANIKO_RELEASE=${{ steps.kaniko.outputs.release }},
            JQ_RELEASE==${{ steps.jq.outputs.release }},
            YQ_RELEASE==${{ steps.yq.outputs.release }},
            PUSHRM_RELEASE==${{ steps.pushrm.outputs.release }}
          tags: woozymasta/kaniko-tools:latest, woozymasta/kaniko-tools:${{ steps.kaniko.outputs.release }}
